name: atm_demand
channels:
  - defaults
  - conda-forge
dependencies:
  - click
  - python=3.8
  - mlflow=1.17.0
  - numpy=1.20.3
  - pandas=1.1.4
  - prophet=1.0
  - scikit-learn=0.24.2
  - tslearn=0.5.1.0
